import { Geist, Geist_Mono } from "next/font/google";
import { SWRConfig } from 'swr';
import "./globals.css";
import { AuthProvider } from '@/contexts/auth-context';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SWRConfig 
          value={{
            revalidateOnFocus: false,
            shouldRetryOnError: false
          }}
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </SWRConfig>
      </body>
    </html>
  );
}
