services:
  backend:
    image: taut0logy/kothakoli-backend:latest
    container_name: kothakoli-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - kothakoli-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 60s
      retries: 3
      start_period: 5s
  frontend:
    depends_on:
      - backend
    image: taut0logy/kothakoli-frontend:latest
    container_name: kothakoli-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://localhost:8000
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - kothakoli-network
networks:
  kothakoli-network:
    driver: bridge
